amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: "scan"
    tf_broadcast: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_vel_x: 0.0
    max_vel_x: 0.3              # Max linear velocity (m/s)
    min_vel_theta: -0.5
    max_vel_theta: 0.5          # Max angular velocity (rad/s)
    acc_lim_x: 2.5
    acc_lim_theta: 3.2
    goal_distance_tol: 0.2
    goal_angle_tol: 0.2
    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.1
    type: "FollowPath"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

recoveries_server:
  ros__parameters:
    use_sim_time: true
    recovery_behaviors: ["spin", "backup"]
    spin:
      plugin: "nav2_recoveries/Spin"
      spin_angle: 1.57
    backup:
      plugin: "nav2_recoveries/BackUp"
      backup_distance: 0.25

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    bt_loop_rate: 10

behavior_server:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true
